# Generated by Django 2.0 on 2019-08-23 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_banner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banner',
            options={'ordering': ['-priority']},
        ),
        migrations.RenameField(
            model_name='banner',
            old_name='position',
            new_name='priority',
        ),
    ]
